### ISSUE TITLE
Don't use a remote icon

### ISSUE THREAD

**Issue by razzeee** [flathub/com.wps.Office#128]
Remote icons are not really supported by flathub right now.

It would be better to use a non remote icon in this repo.

https://github.com/flathub/com.wps.Office/blob/master/com.wps.Office.metainfo.xml#L17

**Comment by razzeee** [comment]
Or additionally copy the icon to the flatpak like https://github.com/flathub/org.onlyoffice.desktopeditors/blob/master/org.onlyoffice.desktopeditors.json#L41 does here for e.g.

**Comment by bevsxyz** [comment]
I think this will be a better icon https://www.wps.com/_content/images/about/logo.png

![](https://www.wps.com/_content/images/about/logo.png)

**Comment by mlawson27** [comment]
I looked at this a little earlier today, and I think the issue now just boils down to the fact that all of the content is downloaded and included in the build during the install phase rather than the download phase, so there's no icon available during build (all of the icons and .desktop files are already included in the .deb file).  I was thinking about extracting just the images during the build phase, but once you go that far, it seems like it makes sense to just extract everything during the build phase rather than have to download and extract twice.

Alternatively, icons and a .desktop file could just be added to the repo and copied during the build (like the VS Code Flatpak does), but since they already exist in the .deb, it seems like less work to just tweak the build script.

I've got a set of changes that seems to work at least locally that does option 1, so I'll just commit that, and I'll just discard it if there's strong objection.

**Comment by mlawson27** [comment]
After playing around with it a little bit, it turns out extracting everything during the build phase pretty significantly increased the download size, so now I think it's easiest to just follow the OnlyOffice and VS Code method of adding the icons and a .desktop file to the repo and installing them during the build phase.  Everything else can mostly remain the same, and the download is smaller.

**Comment by bbhtt** [comment]
Should be fixed now by above.
