### ISSUE TITLE
WPS Writer, WPS Spreadsheets, WPS Presentation does not appear in App Center

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.wps.Office#14]
![captura de tela de 2019-02-01 10-05-49](https://user-images.githubusercontent.com/26097419/52122306-54245200-2601-11e9-93e7-beb8cc1269cf.png)
After the WPS Office installation the WPS Writer, WPS Spreadsheets, WPS Presentation should appear in the App Center

@ramcq Could help?

**Comment by gasinvein** [comment]
As far as I understand, it's @flatpak limitation: only the appstream component with ID matching flatpak app ID is exposed to app stores.

**Comment by LeandroStanger** [comment]
@ramcq Could help?

**Comment by LeandroStanger** [comment]
@ramcq Could help?

**Comment by ramcq** [comment]
Flatpak does correctly export the multiple appstream entries - at present I think this is a GNOME Software limitation in how it matches a Flatpak that exports multiple apps. It's a bit of a pain in Endless OS because we use GNOME Software to add icons to the desktop, so we have the same problem with LibreOffice that if you delete the separate Writer/Calc/etc icons we ship by default on the desktop, you can't add them back without using the CLI or D-Bus API.
