### ISSUE TITLE
The icons have a bad resolution

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.wps.Office#27]
![Captura de tela de 2019-04-03 17-11-32](https://user-images.githubusercontent.com/26097419/55551157-73e2ff80-56b0-11e9-803b-e8e86063ff69.png)

**Comment by gasinvein** [comment]
WPS provides icons for their programs only in 48x48 and 256x256 resolutions. Maybe your launcher is picking the lower-resolution icon when intermediate size is needed?

I'm using this script to check which icon is selected:
```python
#!/usr/bin/env python3

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import sys

if len(sys.argv) != 3:
    raise ValueError('Invalid number of arguments')

icon_theme = Gtk.IconTheme.get_default()

icon_name = sys.argv[1]
icon_size = int(sys.argv[2])

icon = icon_theme.lookup_icon(icon_name, icon_size, 0)
if icon is not None:
    print(icon.get_filename())
else:
    sys.exit(1)
```
You can save it and use like this `./get-icon.py com.wps.Office.wpsmain 128` to check which icon file is picked up by GTK for requested name and size.

**Comment by LeandroStanger** [comment]
Icons 48x48
Endless OS needs 64x64 icons

**Comment by gasinvein** [comment]
So, when EOS launcher needs 64x64 icon for the application but it founds only 48x48 and 256x256, it selects the smaller and stretches it? If so, I'd consider this behavior wrong.

**Comment by ramcq** [comment]
This is just using the code in GNOME Shell to create an app icon, which in turn just uses GAppInfo to get the GIcon, which returns a GThemedIcon, which eventually St loads using the algorithm described in the icon theme spec. https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

So this is behaving according to spec - I think it selects the "closest" size match and 48x48 is closer to 64 than 256 is. It's not always correct to take a large (detailed) icon and scale it down - it can look really bad - so I don't think this spec is wrong either. The app author is best placed to decide which icon should be rendered at which size - anything else is just a fallback heuristic/guess.

Given that 64 and 128 icons are required by the appstream spec anyway, the easiest thing to do is add some resizes to the build process so that you ship your desired/intended icon at these sizes as well . If you search flathub sources for "convert", you will see this is very common: https://github.com/flathub/io.atom.Atom/commit/0c4e77f2

This means the .desktop file will be able to find these sizes from the theme with no scaling/heuristic, but it will also fix another weird thing which is that the appdata files for WPS Office seem to use a remote icon rather than a cached one - this means that eg on https://flathub.org/apps/details/com.wps.Office the icon is loaded from alternativeto.net rather than https://flathub.org/repo/appstream/x86_64/icons/128x128/....

**Comment by gasinvein** [comment]
@ramcq Icons are extracted from extra-data. Wouldn't we need to bundle them and distribute from Flathub to make appstream use cached ones?

**Comment by ramcq** [comment]
Yes, this is desirable - you can just copy them into the GitHub repo. The Flathub position is that it's OK to use the app's icon to refer to the app itself from a trademark perspective because it is https://en.wikipedia.org/wiki/Nominative_use - ie the trademark is being used to refer to what it belongs to.

**Comment by gasinvein** [comment]
Well, WPS Office package doesn't contain the office suite logo (those red with stylized "W"), so we have to grab one from another source anyway.

**Comment by cho2** [comment]
looks blurry on gnome-shell

![Cuplikan layar dari 2019-04-24 13-27-48](https://user-images.githubusercontent.com/6271071/56637065-e5e9ab80-6694-11e9-91d0-b6fdf0cbebed.png)

**Comment by gasinvein** [comment]
Does anyone know alternative source of official WPS icons? The WPS package only contains 48x48 and 256x256.

**Comment by ramcq** [comment]
@gasinvein I think even just downscaling the 256 to 128 and 64 would be better than having shell scale the 48x48 up - might be a good starting point anyway?

**Comment by gasinvein** [comment]
@ramcq I consider resizing a last resort solution, because it would require bundling ImageMagick and making the apply_extra even more complex. But likely we'll have to do so anyway.
BTW, do you know any smaller utility for resizing pngs?

**Comment by ramcq** [comment]
We can copy the icons inside of the github repo and scale them at build time rather than needing to bundle anything. Or even ship the differently scaled copies...

**Comment by gasinvein** [comment]
I think I've found the root of the problem. Icons under 256x256 directory in WPS Office packages are actually 128x128.

**Comment by gasinvein** [comment]
WPS Office now ships app icons of this sizes:
```
16x16
20x20
24x24
32x32
40x40
48x48
60x60
64x64
72x72
80x80
96x96
256x256
512x512
```
@LeandroStanger does the issue still persist?
